### ISSUE TITLE
sys/types.h no such file or directory.. How to add gcc compiler in KEIL IDE.

### ISSUE THREAD

**Issue by sarwadenj** [bjornfor/stm32-test#4]
Hi,

While programming STM32F103C8 board I'm getting following error when i tried to use ARMCC and ARMCLANG, ARM compiler

\platform\syscalls.c(13): error: #5: cannot open source input file "sys/types.h": No such file or directory
-----------------------------------------------------------------------------------------------------------------

As sys/types.h, types.h, sys/stat.h, unistd.h are Newlib implementation then I tried using GCC Compiler(GNU) for ARM Project compiler 

--- Error: failed to execute 'arm-none-eabi-gcc'
![error](https://user-images.githubusercontent.com/20920439/29112989-534cdd46-7d0d-11e7-98cc-e4000295be5e.png)

Thanks.

**Comment by bjornfor** [comment]
Did you see the README file? Your setup is different (Keil vs Eclipse) and I cannot help you. Closing.
